#!/usr/bin/env python
import argparse


import searchebooks


def setup_argparser():
    # Setup the parser
    parser = argparse.ArgumentParser(
        description='''\
Search through content and metadata of ebooks''',
        # RawDescriptionHelpFormatter
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        '-v', '--version', action='version',
        version=f'%(prog)s v{searchebooks.__version__}')
    # ===========
    # Search text
    # ===========
    search_text_group = parser.add_argument_group(title='Search text', description='test')
    search_text_group.add_argument('-t', '--text')
    return parser


def main():
    parser = setup_argparser()
    args = parser.parse_args()
    return 0


if __name__ == '__main__':
    retcode = main()
